const companiesData = [
  {
    id: 1,
    name: "Tata Consultancy Services",
    industry: "IT Services",
    location: "Mumbai, Maharashtra",
    employees: 592000,
    website: "https://www.tcs.com",
  },
  {
    id: 2,
    name: "Infosys",
    industry: "IT Services",
    location: "Bengaluru, Karnataka",
    employees: 335000,
    website: "https://www.infosys.com",
  },
  {
    id: 3,
    name: "Reliance Industries",
    industry: "Oil & Gas",
    location: "Mumbai, Maharashtra",
    employees: 236000,
    website: "https://www.ril.com",
  },
  {
    id: 4,
    name: "HDFC Bank",
    industry: "Banking & Finance",
    location: "Mumbai, Maharashtra",
    employees: 120000,
    website: "https://www.hdfcbank.com",
  },
  {
    id: 5,
    name: "Wipro",
    industry: "IT Services",
    location: "Bengaluru, Karnataka",
    employees: 240000,
    website: "https://www.wipro.com",
  },
  {
    id: 6,
    name: "ICICI Bank",
    industry: "Banking & Finance",
    location: "Mumbai, Maharashtra",
    employees: 97000,
    website: "https://www.icicibank.com",
  },
  {
    id: 7,
    name: "Bharti Airtel",
    industry: "Telecommunications",
    location: "New Delhi, Delhi",
    employees: 18000,
    website: "https://www.airtel.com",
  },
  {
    id: 8,
    name: "Larsen & Toubro",
    industry: "Engineering & Construction",
    location: "Mumbai, Maharashtra",
    employees: 50000,
    website: "https://www.larsentoubro.com",
  },
  {
    id: 9,
    name: "State Bank of India",
    industry: "Banking & Finance",
    location: "Mumbai, Maharashtra",
    employees: 245000,
    website: "https://www.sbi.co.in",
  },
  {
    id: 10,
    name: "Mahindra & Mahindra",
    industry: "Automobile",
    location: "Mumbai, Maharashtra",
    employees: 58000,
    website: "https://www.mahindra.com",
  },
  {
    id: 11,
    name: "Tech Mahindra",
    industry: "IT Services",
    location: "Pune, Maharashtra",
    employees: 141000,
    website: "https://www.techmahindra.com",
  },
  {
    id: 12,
    name: "Adani Enterprises",
    industry: "Infrastructure",
    location: "Ahmedabad, Gujarat",
    employees: 23000,
    website: "https://www.adanienterprises.com",
  },
  {
    id: 13,
    name: "Sun Pharmaceutical",
    industry: "Pharmaceuticals",
    location: "Mumbai, Maharashtra",
    employees: 37000,
    website: "https://www.sunpharma.com",
  },
  {
    id: 14,
    name: "HCL Technologies",
    industry: "IT Services",
    location: "Noida, Uttar Pradesh",
    employees: 222000,
    website: "https://www.hcltech.com",
  },
  {
    id: 15,
    name: "Axis Bank",
    industry: "Banking & Finance",
    location: "Mumbai, Maharashtra",
    employees: 87000,
    website: "https://www.axisbank.com",
  },
  {
    id: 16,
    name: "Maruti Suzuki",
    industry: "Automobile",
    location: "Gurugram, Haryana",
    employees: 38000,
    website: "https://www.marutisuzuki.com",
  },
  {
    id: 17,
    name: "ITC Limited",
    industry: "FMCG",
    location: "Kolkata, West Bengal",
    employees: 35000,
    website: "https://www.itcportal.com",
  },
  {
    id: 18,
    name: "Bajaj Auto",
    industry: "Automobile",
    location: "Pune, Maharashtra",
    employees: 10500,
    website: "https://www.bajajauto.com",
  },
  {
    id: 19,
    name: "Kotak Mahindra Bank",
    industry: "Banking & Finance",
    location: "Mumbai, Maharashtra",
    employees: 78000,
    website: "https://www.kotak.com",
  },
  {
    id: 20,
    name: "Asian Paints",
    industry: "Paints",
    location: "Mumbai, Maharashtra",
    employees: 6500,
    website: "https://www.asianpaints.com",
  },
  {
    id: 21,
    name: "Dr. Reddy's Laboratories",
    industry: "Pharmaceuticals",
    location: "Hyderabad, Telangana",
    employees: 24000,
    website: "https://www.drreddys.com",
  },
  {
    id: 22,
    name: "Hindustan Unilever",
    industry: "FMCG",
    location: "Mumbai, Maharashtra",
    employees: 18000,
    website: "https://www.hul.co.in",
  },
  {
    id: 23,
    name: "Coal India",
    industry: "Mining",
    location: "Kolkata, West Bengal",
    employees: 272000,
    website: "https://www.coalindia.in",
  },
  {
    id: 24,
    name: "NTPC Limited",
    industry: "Power",
    location: "New Delhi, Delhi",
    employees: 19000,
    website: "https://www.ntpc.co.in",
  },
  {
    id: 25,
    name: "Power Grid Corporation",
    industry: "Power",
    location: "Gurugram, Haryana",
    employees: 11000,
    website: "https://www.powergrid.in",
  },
  {
    id: 26,
    name: "Tata Motors",
    industry: "Automobile",
    location: "Mumbai, Maharashtra",
    employees: 78000,
    website: "https://www.tatamotors.com",
  },
  {
    id: 27,
    name: "Tata Steel",
    industry: "Steel",
    location: "Mumbai, Maharashtra",
    employees: 65000,
    website: "https://www.tatasteel.com",
  },
  {
    id: 28,
    name: "JSW Steel",
    industry: "Steel",
    location: "Mumbai, Maharashtra",
    employees: 45000,
    website: "https://www.jsw.in",
  },
  {
    id: 29,
    name: "Cipla",
    industry: "Pharmaceuticals",
    location: "Mumbai, Maharashtra",
    employees: 23000,
    website: "https://www.cipla.com",
  },
  {
    id: 30,
    name: "Hero MotoCorp",
    industry: "Automobile",
    location: "New Delhi, Delhi",
    employees: 10000,
    website: "https://www.heromotocorp.com",
  },
  {
    id: 31,
    name: "Eicher Motors",
    industry: "Automobile",
    location: "Gurugram, Haryana",
    employees: 3500,
    website: "https://www.eicher.in",
  },
  {
    id: 32,
    name: "Britannia Industries",
    industry: "FMCG",
    location: "Kolkata, West Bengal",
    employees: 3800,
    website: "https://www.britannia.co.in",
  },
  {
    id: 33,
    name: "Nestle India",
    industry: "FMCG",
    location: "Gurugram, Haryana",
    employees: 7500,
    website: "https://www.nestle.in",
  },
  {
    id: 34,
    name: "Dabur India",
    industry: "FMCG",
    location: "Ghaziabad, Uttar Pradesh",
    employees: 4200,
    website: "https://www.dabur.com",
  },
  {
    id: 35,
    name: "Godrej Consumer Products",
    industry: "FMCG",
    location: "Mumbai, Maharashtra",
    employees: 1100,
    website: "https://www.godrejcp.com",
  },
  {
    id: 36,
    name: "Zomato",
    industry: "Food Delivery",
    location: "Gurugram, Haryana",
    employees: 3800,
    website: "https://www.zomato.com",
  },
  {
    id: 37,
    name: "Swiggy",
    industry: "Food Delivery",
    location: "Bengaluru, Karnataka",
    employees: 5000,
    website: "https://www.swiggy.com",
  },
  {
    id: 38,
    name: "Flipkart",
    industry: "E-commerce",
    location: "Bengaluru, Karnataka",
    employees: 45000,
    website: "https://www.flipkart.com",
  },
  {
    id: 39,
    name: "Paytm",
    industry: "Fintech",
    location: "Noida, Uttar Pradesh",
    employees: 10000,
    website: "https://www.paytm.com",
  },
  {
    id: 40,
    name: "Byju's",
    industry: "EdTech",
    location: "Bengaluru, Karnataka",
    employees: 11000,
    website: "https://www.byjus.com",
  },
  {
    id: 41,
    name: "Unacademy",
    industry: "EdTech",
    location: "Bengaluru, Karnataka",
    employees: 3000,
    website: "https://www.unacademy.com",
  },
  {
    id: 42,
    name: "Ola Cabs",
    industry: "Transportation",
    location: "Bengaluru, Karnataka",
    employees: 8000,
    website: "https://www.olacabs.com",
  },
  {
    id: 43,
    name: "Oyo Rooms",
    industry: "Hospitality",
    location: "Gurugram, Haryana",
    employees: 5000,
    website: "https://www.oyorooms.com",
  },
  {
    id: 44,
    name: "MakeMyTrip",
    industry: "Travel",
    location: "Gurugram, Haryana",
    employees: 2500,
    website: "https://www.makemytrip.com",
  },
  {
    id: 45,
    name: "Policybazaar",
    industry: "Insurance",
    location: "Gurugram, Haryana",
    employees: 2000,
    website: "https://www.policybazaar.com",
  },
  {
    id: 46,
    name: "Nykaa",
    industry: "E-commerce",
    location: "Mumbai, Maharashtra",
    employees: 1500,
    website: "https://www.nykaa.com",
  },
  {
    id: 47,
    name: "Lenskart",
    industry: "E-commerce",
    location: "Gurugram, Haryana",
    employees: 4000,
    website: "https://www.lenskart.com",
  },
  {
    id: 48,
    name: "Muthoot Finance",
    industry: "Financial Services",
    location: "Kochi, Kerala",
    employees: 25000,
    website: "https://www.muthootfinance.com",
  },
  {
    id: 49,
    name: "Bajaj Finance",
    industry: "Financial Services",
    location: "Pune, Maharashtra",
    employees: 35000,
    website: "https://www.bajajfinserv.in",
  },
  {
    id: 50,
    name: "DLF Limited",
    industry: "Real Estate",
    location: "Gurugram, Haryana",
    employees: 3000,
    website: "https://www.dlf.in",
  },
  {
    id: 51,
    name: "Sobha Limited",
    industry: "Real Estate",
    location: "Bengaluru, Karnataka",
    employees: 4500,
    website: "https://www.sobha.com",
  },
  {
    id: 52,
    name: "Godrej Properties",
    industry: "Real Estate",
    location: "Mumbai, Maharashtra",
    employees: 800,
    website: "https://www.godrejproperties.com",
  },
  {
    id: 53,
    name: "Ambuja Cements",
    industry: "Cement",
    location: "Mumbai, Maharashtra",
    employees: 7000,
    website: "https://www.ambujacement.com",
  },
  {
    id: 54,
    name: "UltraTech Cement",
    industry: "Cement",
    location: "Mumbai, Maharashtra",
    employees: 23000,
    website: "https://www.ultratechcement.com",
  },
  {
    id: 55,
    name: "Grasim Industries",
    industry: "Cement & Textiles",
    location: "Mumbai, Maharashtra",
    employees: 25000,
    website: "https://www.grasim.com",
  },
  {
    id: 56,
    name: "Hindustan Zinc",
    industry: "Mining",
    location: "Udaipur, Rajasthan",
    employees: 15000,
    website: "https://www.hzlindia.com",
  },
  {
    id: 57,
    name: "Vedanta Limited",
    industry: "Mining",
    location: "Mumbai, Maharashtra",
    employees: 75000,
    website: "https://www.vedantalimited.com",
  },
  {
    id: 58,
    name: "Jindal Steel & Power",
    industry: "Steel & Power",
    location: "New Delhi, Delhi",
    employees: 15000,
    website: "https://www.jindalsteelpower.com",
  },
  {
    id: 59,
    name: "Aditya Birla Group",
    industry: "Conglomerate",
    location: "Mumbai, Maharashtra",
    employees: 120000,
    website: "https://www.adityabirla.com",
  },
  {
    id: 60,
    name: "RPG Enterprises",
    industry: "Conglomerate",
    location: "Mumbai, Maharashtra",
    employees: 50000,
    website: "https://www.rpggroup.com",
  },
  {
    id: 61,
    name: "TVS Motor Company",
    industry: "Automobile",
    location: "Chennai, Tamil Nadu",
    employees: 5000,
    website: "https://www.tvsmotor.com",
  },
  {
    id: 62,
    name: "Ashok Leyland",
    industry: "Automobile",
    location: "Chennai, Tamil Nadu",
    employees: 12000,
    website: "https://www.ashokleyland.com",
  },
  {
    id: 63,
    name: "Motherson Sumi",
    industry: "Auto Components",
    location: "Noida, Uttar Pradesh",
    employees: 260000,
    website: "https://www.motherson.com",
  },
  {
    id: 64,
    name: "Bosch India",
    industry: "Auto Components",
    location: "Bengaluru, Karnataka",
    employees: 31000,
    website: "https://www.bosch.in",
  },
  {
    id: 65,
    name: "Bharat Petroleum",
    industry: "Oil & Gas",
    location: "Mumbai, Maharashtra",
    employees: 9000,
    website: "https://www.bharatpetroleum.in",
  },
  {
    id: 66,
    name: "Indian Oil Corporation",
    industry: "Oil & Gas",
    location: "New Delhi, Delhi",
    employees: 33000,
    website: "https://www.iocl.com",
  },
  {
    id: 67,
    name: "GAIL India",
    industry: "Oil & Gas",
    location: "New Delhi, Delhi",
    employees: 4000,
    website: "https://www.gailonline.com",
  },
  {
    id: 68,
    name: "ONGC",
    industry: "Oil & Gas",
    location: "New Delhi, Delhi",
    employees: 33000,
    website: "https://www.ongcindia.com",
  },
  {
    id: 69,
    name: "BHEL",
    industry: "Engineering",
    location: "New Delhi, Delhi",
    employees: 34000,
    website: "https://www.bhel.com",
  },
  {
    id: 70,
    name: "Siemens India",
    industry: "Engineering",
    location: "Mumbai, Maharashtra",
    employees: 10000,
    website: "https://www.siemens.co.in",
  },
  {
    id: 71,
    name: "ABB India",
    industry: "Engineering",
    location: "Bengaluru, Karnataka",
    employees: 9000,
    website: "https://www.abb.co.in",
  },
  {
    id: 72,
    name: "L&T Infotech",
    industry: "IT Services",
    location: "Mumbai, Maharashtra",
    employees: 42000,
    website: "https://www.lntinfotech.com",
  },
  {
    id: 73,
    name: "Mindtree",
    industry: "IT Services",
    location: "Bengaluru, Karnataka",
    employees: 21000,
    website: "https://www.mindtree.com",
  },
  {
    id: 74,
    name: "Mphasis",
    industry: "IT Services",
    location: "Bengaluru, Karnataka",
    employees: 28000,
    website: "https://www.mphasis.com",
  },
  {
    id: 75,
    name: "Hexaware Technologies",
    industry: "IT Services",
    location: "Mumbai, Maharashtra",
    employees: 24000,
    website: "https://www.hexaware.com",
  },
  {
    id: 76,
    name: "Persistent Systems",
    industry: "IT Services",
    location: "Pune, Maharashtra",
    employees: 15000,
    website: "https://www.persistent.com",
  },
  {
    id: 77,
    name: "Cyient",
    industry: "IT Services",
    location: "Hyderabad, Telangana",
    employees: 15000,
    website: "https://www.cyient.com",
  },
  {
    id: 78,
    name: "LTTS",
    industry: "Engineering Services",
    location: "Mumbai, Maharashtra",
    employees: 21000,
    website: "https://www.ltts.com",
  },
  {
    id: 79,
    name: "Tata Elxsi",
    industry: "Design & Technology",
    location: "Bengaluru, Karnataka",
    employees: 10000,
    website: "https://www.tataelxsi.com",
  },
  {
    id: 80,
    name: "Info Edge",
    industry: "Internet",
    location: "Noida, Uttar Pradesh",
    employees: 4000,
    website: "https://www.infoedge.in",
  },
  {
    id: 81,
    name: "Just Dial",
    industry: "Internet",
    location: "Mumbai, Maharashtra",
    employees: 11000,
    website: "https://www.justdial.com",
  },
  {
    id: 82,
    name: "IndiaMART",
    industry: "E-commerce",
    location: "Noida, Uttar Pradesh",
    employees: 3500,
    website: "https://www.indiamart.com",
  },
  {
    id: 83,
    name: "BSE Limited",
    industry: "Financial Services",
    location: "Mumbai, Maharashtra",
    employees: 1000,
    website: "https://www.bseindia.com",
  },
  {
    id: 84,
    name: "NSE India",
    industry: "Financial Services",
    location: "Mumbai, Maharashtra",
    employees: 1200,
    website: "https://www.nseindia.com",
  },
  {
    id: 85,
    name: "CDSL",
    industry: "Financial Services",
    location: "Mumbai, Maharashtra",
    employees: 500,
    website: "https://www.cdslindia.com",
  },
  {
    id: 86,
    name: "Havells India",
    industry: "Electrical Equipment",
    location: "Noida, Uttar Pradesh",
    employees: 5000,
    website: "https://www.havells.com",
  },
  {
    id: 87,
    name: "Crompton Greaves",
    industry: "Electrical Equipment",
    location: "Mumbai, Maharashtra",
    employees: 4000,
    website: "https://www.crompton.co.in",
  },
  {
    id: 88,
    name: "Voltas",
    industry: "Electronics",
    location: "Mumbai, Maharashtra",
    employees: 3500,
    website: "https://www.voltas.com",
  },
  {
    id: 89,
    name: "Blue Star",
    industry: "Electronics",
    location: "Mumbai, Maharashtra",
    employees: 3000,
    website: "https://www.bluestarindia.com",
  },
  {
    id: 90,
    name: "Whirlpool India",
    industry: "Electronics",
    location: "Gurugram, Haryana",
    employees: 4000,
    website: "https://www.whirlpoolindia.com",
  },
  {
    id: 91,
    name: "Titan Company",
    industry: "Luxury Goods",
    location: "Bengaluru, Karnataka",
    employees: 8000,
    website: "https://www.titancompany.in",
  },
  {
    id: 92,
    name: "Kalyan Jewellers",
    industry: "Jewelry",
    location: "Thrissur, Kerala",
    employees: 4000,
    website: "https://www.kalyanjewellers.net",
  },
  {
    id: 93,
    name: "MRF Limited",
    industry: "Tires",
    location: "Chennai, Tamil Nadu",
    employees: 18000,
    website: "https://www.mrftyres.com",
  },
  {
    id: 94,
    name: "Apollo Tyres",
    industry: "Tires",
    location: "Gurugram, Haryana",
    employees: 16000,
    website: "https://www.apollotyres.com",
  },
  {
    id: 95,
    name: "CEAT Limited",
    industry: "Tires",
    location: "Mumbai, Maharashtra",
    employees: 7000,
    website: "https://www.ceat.com",
  },
  {
    id: 96,
    name: "Pidilite Industries",
    industry: "Chemicals",
    location: "Mumbai, Maharashtra",
    employees: 3800,
    website: "https://www.pidilite.com",
  },
  {
    id: 97,
    name: "Asian Granito",
    industry: "Ceramics",
    location: "Ahmedabad, Gujarat",
    employees: 2000,
    website: "https://www.asiangranito.com",
  },
  {
    id: 98,
    name: "Kajaria Ceramics",
    industry: "Ceramics",
    location: "New Delhi, Delhi",
    employees: 3500,
    website: "https://www.kajariaceramics.com",
  },
  {
    id: 99,
    name: "Page Industries",
    industry: "Textiles",
    location: "Bengaluru, Karnataka",
    employees: 35000,
    website: "https://www.pageindustries.com",
  },
  {
    id: 100,
    name: "Arvind Limited",
    industry: "Textiles",
    location: "Ahmedabad, Gujarat",
    employees: 25000,
    website: "https://www.arvind.com",
  },
];

export default companiesData;
